version: '3.8'

name: stratosphere-api

services:
  db:
    container_name: stratosphere-db
    image: postgres:14-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - stratosphere-dbdata:/var/lib/postgresql/data

volumes:
  stratosphere-dbdata:
